### ISSUE TITLE
SkyNumericOptions does not accept currency symbol in lieu of currency ISO code

### ISSUE THREAD

**Issue by Blackbaud-StewartStephens** [blackbaud/skyux-core#115]
It would be convenient if the SkyNumeric pipe accepted a currency symbol OR a currency ISO code.  Unfortunately we don't always know the ISO but we are sometimes given the currency symbol instead.  In this case it would be convenient to supply the currency symbol directly, rather than try to look up the ISO based on the symbol.

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-StewartStephens could you provide a little more background information on the use case for not knowing the ISO code but having the currency symbol? 

We delegate through our pipe to Angular's Currency Pipe which does not accept symbols so to do this we will have to implement some custom logic to determine ISO based on symbol. We were just curious about the use case here before we discuss this more as a team.

**Comment by Blackbaud-StewartStephens** [comment]
I'm not totally familiar with the implementation, but as I understand it RE7 doesn't actually have a way to set the organization's currency code.  It sounds like the RENXT service tries to guess the currency code based on the country code and some other settings but it doesn't always succeed, and when it fails it simply returns an empty string for the currency code.

As a temporary workaround I wrote a function that maps currency symbols back to rather arbitrary country codes that use that symbol, which sounds like what you're proposing.  It's disappointing that we can't set the currency symbol directly, but if we have to do this mapping it would be nice for it to be in a single place, since we'll have to do something similar for other SPAs as well.

https://blackbaud.visualstudio.com/Products/_git/skyux-spa-gift?path=%2Fsrc%2Fapp%2Fapp-extras.module.ts&version=GBmaster&line=313&lineEnd=313&lineStartColumn=1&lineEndColumn=70&lineStyle=plain

**Comment by Blackbaud-StewartStephens** [comment]
The Events SPA is also doing something a little bit different, using the numeric pipe and just prepending the currency symbol.

https://blackbaud.visualstudio.com/Products/_git/skyux-lib-events-components?path=%2Fsrc%2Fapp%2Fpublic%2Fmodules%2Fshared%2Fpipes%2Fcurrency-symbol.pipe.ts&version=GBmaster&_a=content

**Comment by Blackbaud-ThomasOrtiz** [comment]
FENXT will also run into this issue.

As an example, FENXT allows clients to set custom currency settings such as: 
- **Currency symbol**
- **Digit grouping symbol**
- **Number of digits after decimal**
- **Negative currency format**

The complexities of our custom currency options means FENXT will probably need to create our own custom pipe/service but we could always use a new Sky pipe _(that could be passed a custom currency symbol)_ as a base and extend off of that.
