### ISSUE TITLE
SkyDynamicComponentService uses deprecated SkyWindowRefService

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [blackbaud/skyux-core#144]
### Expected behavior

The deprecated service should be removed from non-deprecated classes or those classes should also be deprecated.

### Actual behavior

`SkyDynamicComponentService` is not deprecated but uses the deprecated `SkyWindowRefService`. When I create a unit test which provides `SkyWaitService`, I must provide `SkyDynamicComponentService` and therefore `SkyWindowRefService`. 

When I run `skyux test` with these providers, I see `WARNING: 45:17  deprecation       SkyWindowRefService is deprecated: Use `SkyAppWindowRef` instead.`

### Steps to reproduce

The following test of a component that has a button that triggers a blocking page wait will generate this warning:
```
import {ComponentFixture, TestBed} from '@angular/core/testing';
import {expect} from '@skyux-sdk/testing';
import {SkyWaitService} from '@skyux/indicators';
import {MySampleComponent} from './my.component';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import {SkyWaitPageAdapterService} from '@skyux/indicators/modules/wait/wait-page-adapter.service';
import {SkyWindowRefService, SkyDynamicComponentService} from '@skyux/core';

describe('MySampleComponent', () => {
    let component: MySampleComponent;
    let fixture: ComponentFixture<MySampleComponent>;
    let waitService: SkyWaitService;
    let componentElements: any;

    beforeEach(() => {
        TestBed.configureTestingModule({
            imports: [
                FormsModule,
                ReactiveFormsModule
            ],
            providers: [
                SkyWaitService,
                SkyWaitPageAdapterService,
                SkyWindowRefService,
                SkyDynamicComponentService
            ],
            declarations: [
                MySampleComponent
            ]
        });
    });

    beforeEach(() => {
        fixture = TestBed.createComponent(MySampleComponent);
        waitService = TestBed.get(SkyWaitService);
        component = fixture.componentInstance;

        componentElements = {
            myButton: (): HTMLButtonElement => fixture.nativeElement.querySelector('button#myButton')
        };
        fixture.detectChanges();
    });

    it('should update privacy policy when policy update button is clicked', () => {
        fixture.detectChanges();

        spyOn(waitService, 'beginBlockingPageWait');
        spyOn(waitService, 'endBlockingPageWait');

        componentElements.myButton().click();

        expect(waitService.beginBlockingPageWait).toHaveBeenCalled();
        expect(waitService.endBlockingPageWait).toHaveBeenCalled();
    });
});
```

### Severity

Low, this just generates a warning during tests and shows a yellow squiggle warning in VS Code. I did waste some time trying to follow the instructions to replace the deprecated class which led to test failure due to the missing provider.

### Impact

`SkyDynamicComponentService` is used by many SKY components so this probably affects many tests.

**Comment by Blackbaud-BobbyEarl** [comment]
For some additional context, this is known and expected behavior.  It will require a breaking change to address.

https://github.com/blackbaud/skyux-core/blob/master/CHANGELOG.md#390-2019-11-22

**Comment by Blackbaud-ChristiSchneider** [comment]
Will `SkyDynamicComponentService` be deprecated/removed or will it just stop using the deprecated stuff?

**Comment by Blackbaud-BobbyEarl** [comment]
It will be updated to not use the deprecated stuff.
