### ISSUE TITLE
SkyNumericPipe: Better typing

### ISSUE THREAD

**Issue by ThomasOrtiz** [blackbaud/skyux-core#178]
### Expected behavior
SkyNumeric Pipe should have typing on its transform

- [Transform link](https://github.com/blackbaud/skyux-core/blob/21e876f5bdc2217497556080ee8f4e0933a88176/src/app/public/modules/numeric/numeric.pipe.ts#L55)
  - `config` should be typed based off [numeric options documentation](https://developer.blackbaud.com/skyux/components/numeric#numericoptions-properties) rather than `any`.

### Actual behavior

- `config` is typed as an `any`.

**Comment by Tdortiz** [comment]
It looks like deep down Sky ends up using the [Intl Api](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat) in [skyux/i18n's number formatter](https://github.com/blackbaud/skyux-i18n/blob/116a131a8d42ecad57df433f23b489f0966fe2ff/src/app/public/modules/i18n/intl-number-formatter.ts#L41).

Shouldn't all these options be available to us if we want?

**Comment by Blackbaud-SteveBrush** [comment]
@Tdortiz For that last comment, would you mind creating a new issue since it appears to be a slightly different question?

**Comment by Tdortiz** [comment]
@Blackbaud-SteveBrush Will do!

**Comment by Tdortiz** [comment]
Created the new issue at #179 and updated the comment in this issue.
