### ISSUE TITLE
Add support for Windows 10 Edge 44

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-core#51]
The numeric service (specifically Angular 4's `CurrencyPipe`) does not work with Microsoft Edge, version 44 (EdgeHTML version 18).

This will automatically be fixed when we support versions of Angular greater than 4.

**(We've temporarily disabled unit tests for Edge; this will need to be rectified when we get on Angular 7!)**

**Comment by Blackbaud-TrevorBurch** [comment]
This bug was fixed by previous releases. All unit tests have been renabled.
