### ISSUE TITLE
Navigate to anchor links on a page

### ISSUE THREAD

**Issue by blackbaud-brandonhare** [blackbaud/skyux-core#66]
### Expected behavior
When I navigate to a route that has a hash fragment, the page should load scrolled to that section.

### Actual behavior
It loads at the top of the page.
### Steps to reproduce
Add a router link with a fragment to a page with an element with that ID and click it. 

This has been an open issue in Angular 2 for a year and a half now, so if we can add support for it with the SkyRouterLink directive, that would be awesome: https://github.com/angular/angular/issues/6595

**Comment by nkoehler** [comment]
Still open? Can we get an update on this...

**Comment by Blackbaud-AlexKingman** [comment]
Possibly fixed: https://github.com/angular/angular/pull/20030

**Comment by Blackbaud-AlexKingman** [comment]
Closing, this is working since Angular 6.1, and is also currently working for Stache sites.
