### ISSUE TITLE
Research ability to maintain state for certain page elements

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux-core#68]
From @Blackbaud-MattGregg SPA Navigation guidelines.

Research ability to maintain state across sessions for:

- [x] Tile position
- [x] Tile expand/collapse states
- [ ] Selected tab
- [x] Lists (sort order, column choices, view mode)
- [ ] Page context

**Comment by Blackbaud-AlexKingman** [comment]
Closing - Solved for the majority of these items. For scenarios like page context / selected tabs, we may be able to use the UI Config Service as a solution.
