### ISSUE TITLE
SkyNumericPipe does not support other locales

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-core#75]
### Expected behavior

`SkyNumericPipe` should support locales other than `en-US`.

### Actual behavior

It only supports `en-US`.

FYI: we recently added Angular 4's `intl` utility to our `SkyNumericPipe` source.
Related pull request: https://github.com/blackbaud/skyux-core/pull/74

**Comment by Blackbaud-SteveBrush** [comment]
Closing as I believe this feature has been completed. We can reopen if the problem persists.

**Comment by Blackbaud-AlexKingman** [comment]
Available in `@skyux/core@4.1.0`
