### ISSUE TITLE
Can't find variable: Intl on Mobile Safari 9.0

### ISSUE THREAD

**Issue by blackbaud-GavinNicol** [blackbaud/skyux-core#97]
### Expected behavior

The SkyNumeric Service/Pipe should work on Mobile Safari 9.0

### Actual behavior

Loading pages that use the SkyNumeric service/pipe on iOS 9 lead to `Can't find variable: Intl`

We've had clients from multiple organizations run into this issue on their iPads.

**Comment by Blackbaud-SteveBrush** [comment]
@blackbaud-GavinNicol As you know, we do not support that version of iOS. However, you can implement a third-party polyfill for the `Intl` utility: 
https://github.com/andyearnshaw/Intl.js/#intljs-and-node

**app-extras.module.ts**
```
const intlPolyfill = require('intl');

if (!(window as any).Intl) {
  (window as any).Intl = intlPolyfill;
}

@NgModule({
  exports: []
})
export class AppExtrasModule { }
```
